/**
 * generated by Xtext
 */
package org.larz.dom4.dm.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DmProposalProvider /* implements AbstractDmProposalProvider  */{
}
