/*
 * generated by Xtext
 */
package org.larz.dom4.dm.ui.contentassist

import org.larz.dom4.dm.ui.contentassist.AbstractDmProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DmProposalProvider extends AbstractDmProposalProvider {
}
